Implemented posting Twitch Live notifications to Discord Channels
FragSoc/esports-bot pull request #140
Opened 2021-06-26 23:13 UTC by Fluxticks

Implemented use of Twitch API and webhooks to receive notifications of when streamers go live. 

This resolves #14

2021-06-27 00:05 UTC, Laura7089 commented
You'll need to merge from master

2021-06-27 12:36 UTC, Fluxticks commented
Am I meant to be merging straight into master?

2021-06-27 14:21 UTC, Laura7089 commented
Sorry, `develop` - you'll need to merge develop into this to get ryan's database changes.

2021-06-27 14:25 UTC, Fluxticks commented
Oh yeah I did that already with commit #[0269886](https://github.com/FragSoc/esports-bot/pull/140/commits/02698866d6a693b6905f38f9da8ec25234c4616a)

2021-06-28 11:06 UTC, Laura7089 requested changes
Awesome stuff. Will the web server need a port forwarding? Is the README up to date?

2021-06-28 11:06 UTC, Laura7089 commented on src/esportsbot/cogs/TwitchCog.py
> +            if message is not None and message.strip() == "" or message == "":
The last part of this bool isn't necessary

2021-06-28 11:06 UTC, Laura7089 commented on src/esportsbot/cogs/TwitchCog.py
> +    # TODO: Probably best to move this to lib or some other as it is shared by TwitterCog
Still relevant?

2021-06-28 11:06 UTC, Laura7089 commented on src/esportsbot/cogs/TwitchCog.py
> +    # TODO: Probably best to move this to lib or some other as it is shared by TwitterCog
Again, TODO still relevant?

2021-06-28 11:08 UTC, Laura7089 commented on src/esportsbot/cogs/TwitchCog.py
> +            with open("bearer", "w") as f:
Perhaps https://docs.python.org/3/library/tempfile.html? Depends how long you want the file to live really

2021-07-04 17:51 UTC, Laura7089 commented
Closes #14

2021-07-05 14:49 UTC, Fluxticks commented on src/esportsbot/cogs/TwitchCog.py
> +        # TODO: Capture this event to determine when a webhook gets deleted not using the command.
Yeah I haven't figured out how to properly make use of this event but it is something that would be good to implement.

2021-07-05 14:50 UTC, Fluxticks commented
I implemented most, if not all, of the changes you suggested, thanks :)

2021-07-05 15:10 UTC, Laura7089 commented on src/esportsbot/cogs/TwitchCog.py
> +        # TODO: Capture this event to determine when a webhook gets deleted not using the command.
Cool, if there's nothing to be done immediately we're probably fine committing this as-is

2021-07-05 15:14 UTC, Laura7089 approved these changes

2021-07-05 16:24 UTC, Laura7089 commented
> Awesome stuff. Will the web server need a port forwarding? Is the README up to date?

Bump on these

2021-07-05 16:29 UTC, Fluxticks commented
README is up to date yes, and yes it will need portforwarding

2021-07-05 16:50 UTC, Laura7089 commented
> it will need portforwarding

You'll want to open the port in the docker-compose file. I can do that if you want (what port)?

2021-07-06 09:11 UTC, Fluxticks commented
Yeah it currently binds itself to port 443, but if you could do the docker port thing for me that'd be great :)

2021-07-23 15:24 UTC, Laura7089 commented
Sorry, I never saw your reply :(
Does this need TLS?

2021-07-23 17:13 UTC, Fluxticks commented
Er, my networking knowledge is very limited so not sure. I used ngrok for all of the network stuff while developing so all I know is the port number

2021-07-24 08:49 UTC, Laura7089 commented
If it worked during your testing with the official twitch api, it's probably fine, I'll take a look at the official doc to be doubly sure

2021-07-24 08:51 UTC, Laura7089 commented
Scratch that, it does need https as mentioned here https://dev.twitch.tv/docs/eventsub

2021-08-19 15:18 UTC, merged