Fixed some bugs and made some enhancements in the MusicCog
FragSoc/esports-bot pull request #67
Opened 2021-05-13 22:38 UTC by Fluxticks

- Fixed bugs to do with the time allowance not resetting
 - Changed where message deletions happen, now moved to the on_message method
 - Added a volume command so users can change the volume during playback
 - Added resetallowance command to allow admins to manually reset stuck allowances

2021-05-23 18:10 UTC, Trimatix commented
https://discordpy.readthedocs.io/en/latest/intro.html
Need to update `src/requirements.txt` from `discord.py` to `discord.py[voice]`

@Laura7089 pls can apt installs of `libffi-dev`, `libnacl-dev` and `python3-dev` be added to the dockerfile?

2021-05-23 18:20 UTC, Trimatix approved these changes
Great stuff, cheers for the aliases. Help strings would be great too, just use the `help=""` arg for the command decorator. Could also add a `usage=""` if you wanted to

2021-05-23 18:20 UTC, Trimatix commented on src/esportsbot/cogs/MusicCog.py
> +    def __get_youtube_api_info(request: str, message_type: int) -> Union[List[dict], None]:
Since it's static, this could even be moved outside of the class

2021-05-23 18:20 UTC, Trimatix commented on src/esportsbot/cogs/MusicCog.py
> +    def __get_opus_stream(formats: list) -> Tuple[str, float]:
move outside of class? may or may not be appropriate, idk

2021-05-23 18:20 UTC, Trimatix commented on src/esportsbot/cogs/MusicCog.py
> +    def __is_url(string: str) -> bool:
move outside of class?

2021-05-23 18:20 UTC, Trimatix commented on src/esportsbot/cogs/MusicCog.py
> +    def __song_list_to_string(songs: list) -> str:
move outside of class?

2021-05-25 12:44 UTC, Laura7089 commented
> @Laura7089 pls can apt installs of `libffi-dev`, `libnacl-dev` and `python3-dev` be added to the dockerfile?

Can do, but you might find that `python3-dev` in particular makes the image *massive* - is there any way we can get around that dep?

2021-05-28 13:43 UTC, Laura7089 approved these changes

2021-05-31 10:26 UTC, Trimatix requested changes

2021-05-31 10:26 UTC, Trimatix commented on src/esportsbot/bot.py
> +        elif message.guild is not None and message.role_mentions:
This means that roles can be ping spammed in the music channel without triggering cooldown
Please see my `on_message` implementation i provided [in discord](https://discord.com/channels/213011069671571456/818102325172109332/841002357097496608)

2021-06-01 20:39 UTC, Laura7089 approved these changes
Great stuff :D

2021-06-02 17:54 UTC, Trimatix approved these changes

2021-06-03 13:47 UTC, merged